# Generated by Django 5.2.4 on 2025-07-30 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="edited",
            field=models.BooleanField(
                default=False, help_text="Whether the message has been edited"
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="edited_at",
            field=models.DateTimeField(
                blank=True, help_text="When the message was last edited", null=True
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_message", "New Message"),
                    ("message_read", "Message Read"),
                    ("message_edited", "Message Edited"),
                    ("user_online", "User Online"),
                    ("user_offline", "User Offline"),
                ],
                default="new_message",
                help_text="Type of notification",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MessageHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_content",
                    models.TextField(
                        help_text="The previous content before the edit",
                        max_length=1000,
                    ),
                ),
                (
                    "edited_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the edit was made",
                    ),
                ),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, help_text="Version number of this edit"
                    ),
                ),
                (
                    "edited_by",
                    models.ForeignKey(
                        help_text="The user who made the edit",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_edits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        help_text="The message this history entry belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="messaging.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message History",
                "verbose_name_plural": "Message Histories",
                "ordering": ["-edited_at"],
                "unique_together": {("message", "version")},
            },
        ),
    ]
