# Generated by Django 5.2.4 on 2025-07-30 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_message_edited_message_edited_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                help_text="The message this is a reply to (for threaded conversations)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="messaging.message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="read_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the message was read by the receiver",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="thread_level",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The depth level in the conversation thread (0 for root messages)",
            ),
        ),
    ]
