# Generated by Django 5.2.4 on 2025-07-18 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messages_convers_38b855_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messages_sender__7375e3_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='When the message was sent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text="User's first name", max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, help_text="User's last name", max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text="User's password (hashed)", max_length=128),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-sent_at'], name='messages_convers_1401f8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-sent_at'], name='messages_sender__a8857b_idx'),
        ),
    ]
